name: sftp-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - run: npm ci
      - run: npm run build --if-present      
      
      - name: Deploy to SFTP
        uses: Samkirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
