name: sftp-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Build
        run: |
          npm install
          npm run build --if-present      
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public
          method: sftp
          port: 21
